package modelo;

public enum Categoria {
    BURACO_NA_RUA,
    ILUMINACAO_QUEBRADA,
    LIXO_ACUMULADO,
    ESGOTO_VAZANDO,
    ARVORE_CAIDA,
    VAZAMENTO_DE_AGUA,
    BARULHO_EXCESSIVO,
    CALCADA_DANIFICADA,
    SEMAFORO_COM_DEFEITO,
    OUTROS
}
